[package]
name = "material-color-utilities"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
color-eyre = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
plotters = "0.3.7"
statrs = "0.18.0"
rand = "0.10.0"
image = "0.24.9"