[package]
name = "material-color-utilities"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
color-eyre = "0.6.5"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"